### ISSUE TITLE
Building packages is not working on Travis

### ISSUE THREAD

**Issue by Mikanebu** [zeit/pkg#144]
We are trying to build on travis and getting error:
No such file or directory - packed/* (Errno::ENOENT)
Probably, it is failing to build executables.

This is travis config:
```
before_deploy: npm run pack
deploy: 
  provider: releases
  api_key:
    secure: "encrypted token"
  file: "packed/*"
  skip_cleanup: true
  on: 
    tags: true
```
This is pkg config in package.json:
```
{
  ...
  "scripts": {
     ...
    "pack": "pkg bin/data.js -c package.json -o packed/datahub"
  },
  ...
  "pkg": {
    "scripts": [
      "bin/*",
      "lib/**/*"
    ],
    "targets": [
      "node7-linux-x64",
      "node7-macos-x64"
    ]
  }
}
```
